version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    networks:
      - demo
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 30s
      retries: 5

  redis:
    image: redis:6-alpine
    container_name: redis
    networks:
      - demo
    volumes:
      - redis_storage:/data
    ports:
      - "6379:6379"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET}
      - N8N_REDIS_HOST=redis
    volumes:
      - n8n_storage:/home/node/.n8n
    networks:
      - demo
    depends_on:
      - postgres
      - redis

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - demo

  ollama-cpu:
    image: ollama/ollama:latest
    container_name: ollama-cpu
    command: "serve"
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    networks:
      - demo
    depends_on:
      - redis

  ollama-pull-llama-cpu:
    image: ollama/ollama:latest
    container_name: ollama-pull-llama-cpu
    entrypoint: /bin/sh
    command:
      - "-c"
      - "sleep 3; OLLAMA_HOST=ollama-cpu:11434 ollama pull llama3.2; OLLAMA_HOST=ollama-cpu:11434 ollama pull nomic-embed-text"
    volumes:
      - ollama_storage:/root/.ollama
    networks:
      - demo
    depends_on:
      - ollama-cpu

networks:
  demo:
    driver: bridge

volumes:
  postgres_storage:
  redis_storage:
  qdrant_storage:
  n8n_storage:
  ollama_storage:
