version: '3.8'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - SERVICE_FQDN_N8N_5678
      - 'N8N_EDITOR_BASE_URL=${SERVICE_FQDN_N8N}'
      - 'WEBHOOK_URL=${SERVICE_FQDN_N8N}'
      - 'N8N_HOST=${SERVICE_URL_N8N}'
      - DB_POSTGRESDB_HOST=postgresql
      - DB_POSTGRESDB_PORT=5432
      - 'DB_POSTGRESDB_DATABASE=${POSTGRES_DB}'
      - 'DB_POSTGRESDB_USER=${POSTGRES_USER}'
      - 'DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}'
    volumes:
      - 'n8n-data:/home/node/.n8n'
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'
      interval: 10s
      timeout: 30s
      retries: 5
  postgresql:
    image: 'postgres:16-alpine'
    volumes:
      - 'postgres_storage:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'      
    healthcheck:
      test:
        - CMD-SHELL
        - 'test -S /var/run/postgresql/.s.PGSQL.5432'
      interval: 10s
      timeout: 30s
      retries: 5
  redis:
    image: 'redis:6-alpine'
    container_name: redis
    networks:
      - demo
    volumes:
      - 'redis_storage:/data'
    ports:
      - '6379:6379'
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - '6333:6333'
    volumes:
      - 'qdrant_storage:/qdrant/storage'
    networks:
      - demo
  ollama-cpu:
    image: 'ollama/ollama:latest'
    container_name: ollama-cpu
    command: serve
    ports:
      - '11434:11434'
    volumes:
      - 'ollama_storage:/root/.ollama'
    networks:
      - demo
    depends_on:
      - redis
  ollama-pull-llama-cpu:
    image: 'ollama/ollama:latest'
    container_name: ollama-pull-llama-cpu
    entrypoint: /bin/sh
    command:
      - '-c'
      - 'sleep 3; OLLAMA_HOST=ollama-cpu:11434 ollama pull llama3.2; OLLAMA_HOST=ollama-cpu:11434 ollama pull nomic-embed-text'
    volumes:
      - 'ollama_storage:/root/.ollama'
    networks:
      - demo
    depends_on:
      - ollama-cpu
networks:
  demo:
    driver: bridge
volumes:
  postgres_storage: null
  redis_storage: null
  qdrant_storage: null
  n8n_storage: null
  ollama_storage: null
